#!/usr/bin/env bash
# Forge Prime install script
# One-command install on Mac or EC2 Ubuntu
# Usage: bash install.sh

set -euo pipefail

FORGE_HOME="$HOME/.forge-prime"
FORGE_STATE="$HOME/.forge/prime"
WIKI_DIR="$FORGE_STATE/wiki"
CLAUDE_DIR="$HOME/.claude"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log() { printf "\033[1;34m[forge-prime]\033[0m %s\n" "$*"; }
ok()  { printf "\033[1;32m[forge-prime]\033[0m ✓ %s\n" "$*"; }
warn(){ printf "\033[1;33m[forge-prime]\033[0m ⚠ %s\n" "$*"; }
fail(){ printf "\033[1;31m[forge-prime]\033[0m ✗ %s\n" "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Step 1: Prerequisites
# ---------------------------------------------------------------------------
log "Checking prerequisites…"

python3 --version >/dev/null 2>&1 || fail "Python 3 not found. Install Python 3.11+"
PY_MINOR=$(python3 -c "import sys; print(sys.version_info.minor)")
[ "$PY_MINOR" -lt 11 ] && fail "Python 3.11+ required (found 3.$PY_MINOR)"
ok "Python 3.$PY_MINOR"

git --version >/dev/null 2>&1 || fail "git not found"
ok "git"

jq --version >/dev/null 2>&1 && ok "jq" || warn "jq not found (optional)"

command -v claude >/dev/null 2>&1 && ok "claude cli" || warn "claude cli not found — runner will not work without it"

# ---------------------------------------------------------------------------
# Step 2: Python dependencies
# ---------------------------------------------------------------------------
log "Installing Python dependencies…"
pip install -r "$SCRIPT_DIR/requirements.txt" --break-system-packages --quiet \
  || pip install -r "$SCRIPT_DIR/requirements.txt" --quiet \
  || fail "pip install failed"
ok "Python deps installed"

# ---------------------------------------------------------------------------
# Step 3: Backup existing ~/.claude if present
# ---------------------------------------------------------------------------
if [ -d "$CLAUDE_DIR" ]; then
  BACKUP="$HOME/.claude.backup.$(date +%Y%m%d%H%M%S)"
  log "Backing up existing ~/.claude to $BACKUP"
  cp -r "$CLAUDE_DIR" "$BACKUP"
fi

# ---------------------------------------------------------------------------
# Step 4: Copy claude/ → ~/.claude/
# ---------------------------------------------------------------------------
log "Installing Claude OS layer to ~/.claude/…"
mkdir -p "$CLAUDE_DIR"
cp -r "$SCRIPT_DIR/claude/." "$CLAUDE_DIR/"
ok "Claude OS layer installed"

# ---------------------------------------------------------------------------
# Step 5: Create wiki directory structure
# ---------------------------------------------------------------------------
log "Creating wiki directory structure…"
mkdir -p "$WIKI_DIR/staging"
mkdir -p "$WIKI_DIR/articles/patterns"
mkdir -p "$WIKI_DIR/articles/anti-patterns"
mkdir -p "$WIKI_DIR/articles/decisions"
mkdir -p "$WIKI_DIR/articles/domain"
if [ ! -f "$WIKI_DIR/index.md" ]; then
  cat > "$WIKI_DIR/index.md" <<'EOF'
# Forge Prime Wiki
This wiki grows with every project. Agents read this before coding.
Index is regenerated by `forge compile`. Articles live in articles/.
EOF
fi
ok "Wiki directories created"

# ---------------------------------------------------------------------------
# Step 6: Create forge state directories
# ---------------------------------------------------------------------------
log "Creating forge state dirs…"
mkdir -p "$FORGE_STATE/db"
mkdir -p "$FORGE_HOME"

# Create .env with OpenRouter key placeholder
ENV_FILE="$FORGE_HOME/.env"
if [ ! -f "$ENV_FILE" ]; then
  cat > "$ENV_FILE" <<'EOF'
OPENROUTER_API_KEY=
FORGE_DEFAULT_MODEL=sonnet
EOF
  ok "Created $ENV_FILE (fill in OPENROUTER_API_KEY)"
else
  log ".env already exists — skipping"
fi

# ---------------------------------------------------------------------------
# Step 7: Install forge binary
# ---------------------------------------------------------------------------
log "Installing forge CLI…"
chmod +x "$SCRIPT_DIR/bin/forge"
if [ -w /usr/local/bin ]; then
  ln -sf "$SCRIPT_DIR/bin/forge" /usr/local/bin/forge
  ok "Installed forge → /usr/local/bin/forge"
else
  ln -sf "$SCRIPT_DIR/bin/forge" "$HOME/.local/bin/forge" 2>/dev/null || warn "Could not symlink forge binary — add $SCRIPT_DIR/bin to PATH"
fi

# ---------------------------------------------------------------------------
# Step 8: Install systemd service (Linux) / LaunchAgent (Mac)
# ---------------------------------------------------------------------------
OS="$(uname -s)"
if [ "$OS" = "Linux" ] && command -v systemctl >/dev/null 2>&1; then
  log "Installing forge-dashboard systemd service…"
  DASHBOARD_SERVICE="$SCRIPT_DIR/systemd/forge-dashboard.service"
  if [ -f "$DASHBOARD_SERVICE" ]; then
    # Substitute actual paths into the service file
    sed "s|FORGE_PRIME_DIR|$SCRIPT_DIR|g" "$DASHBOARD_SERVICE" > /tmp/forge-dashboard.service
    sudo cp /tmp/forge-dashboard.service /etc/systemd/system/forge-dashboard.service 2>/dev/null \
      || warn "Could not install systemd service (no sudo). Run manually: uvicorn dashboard.app:app --port 8099"
    sudo systemctl daemon-reload 2>/dev/null && sudo systemctl enable forge-dashboard 2>/dev/null \
      || warn "Could not enable systemd service"
  fi
elif [ "$OS" = "Darwin" ]; then
  log "macOS: creating LaunchAgent for dashboard…"
  LAUNCH_DIR="$HOME/Library/LaunchAgents"
  mkdir -p "$LAUNCH_DIR"
  PLIST_PATH="$LAUNCH_DIR/com.forge-prime.dashboard.plist"
  cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.forge-prime.dashboard</string>
  <key>ProgramArguments</key>
  <array>
    <string>$(which python3)</string>
    <string>-m</string><string>uvicorn</string>
    <string>dashboard.app:app</string>
    <string>--host</string><string>0.0.0.0</string>
    <string>--port</string><string>8099</string>
  </array>
  <key>WorkingDirectory</key><string>$SCRIPT_DIR</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$FORGE_HOME/dashboard.log</string>
  <key>StandardErrorPath</key><string>$FORGE_HOME/dashboard.err</string>
</dict>
</plist>
EOF
  launchctl load "$PLIST_PATH" 2>/dev/null && ok "LaunchAgent installed" \
    || warn "Could not load LaunchAgent — run: launchctl load $PLIST_PATH"
fi

# ---------------------------------------------------------------------------
# Step 9: Start dashboard
# ---------------------------------------------------------------------------
log "Starting dashboard…"
if command -v systemctl >/dev/null 2>&1 && systemctl is-enabled forge-dashboard &>/dev/null; then
  sudo systemctl start forge-dashboard 2>/dev/null && ok "Dashboard started via systemd" \
    || warn "Could not start via systemd"
fi

# ---------------------------------------------------------------------------
# Step 10: Install weekly wiki compile cron
# ---------------------------------------------------------------------------
log "Installing weekly wiki compile cron (Sunday 2am)…"
CRON_LINE="0 2 * * 0 cd $SCRIPT_DIR && forge compile >> $FORGE_HOME/compile.log 2>&1"
( crontab -l 2>/dev/null | grep -v "forge compile"; echo "$CRON_LINE" ) | crontab - 2>/dev/null \
  && ok "Weekly wiki compile cron installed" \
  || warn "Could not install cron — add manually: $CRON_LINE"

# ---------------------------------------------------------------------------
# Step 11: Create Obsidian vault symlink
# ---------------------------------------------------------------------------
ln -sf "$WIKI_DIR" "$HOME/.obsidian-vault" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Step 12: forge doctor
# ---------------------------------------------------------------------------
log "Running forge doctor…"
"$SCRIPT_DIR/bin/forge" doctor || true

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Forge Prime installed."
echo "  Dashboard:      http://localhost:8099"
echo "  Wiki repo:      https://github.com/nimishshah1989/forge-prime-wiki"
echo "  Obsidian vault: ~/.obsidian-vault (→ $WIKI_DIR)"
echo "  Add your OpenRouter key: $FORGE_HOME/.env"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
