"""Wiki compiler: staging → articles/ → index.md."""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

WIKI_DIR = Path.home() / ".forge" / "prime" / "wiki"
STAGING = WIKI_DIR / "staging"
ARTICLES = WIKI_DIR / "articles"
INDEX = WIKI_DIR / "index.md"

VALID_CATEGORIES = {"patterns", "anti-patterns", "decisions", "domain"}


def _parse_frontmatter(text: str) -> dict[str, str]:
    meta: dict[str, str] = {}
    if not text.startswith("---"):
        return meta
    end = text.find("---", 3)
    if end == -1:
        return meta
    fm = text[3:end].strip()
    for line in fm.splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            meta[k.strip()] = v.strip()
    return meta


def compile_wiki() -> None:
    if not STAGING.exists():
        STAGING.mkdir(parents=True, exist_ok=True)

    # Move staging articles to articles/ by category
    staged = list(STAGING.glob("*.md"))
    for src in staged:
        text = src.read_text(errors="replace")
        meta = _parse_frontmatter(text)
        category = meta.get("category", "decisions")
        if category not in VALID_CATEGORIES:
            category = "decisions"
        dest_dir = ARTICLES / category
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest = dest_dir / src.name
        # Deduplicate by title
        title = meta.get("title", src.stem)
        existing = _find_by_title(title, category)
        if existing and existing != dest:
            existing.unlink()
        shutil.move(str(src), str(dest))

    # Build index.md
    lines = ["# Forge Prime Wiki\n", "Index regenerated by `forge compile`.\n\n"]
    total = 0
    for category in sorted(VALID_CATEGORIES):
        cat_dir = ARTICLES / category
        if not cat_dir.exists():
            continue
        articles = sorted(cat_dir.glob("*.md"))
        if not articles:
            continue
        lines.append(f"## {category.title()}\n\n")
        for art in articles:
            text = art.read_text(errors="replace")
            meta = _parse_frontmatter(text)
            title = meta.get("title", art.stem)
            chunk_id = meta.get("chunk_id", "")
            summary = _first_paragraph(text)
            lines.append(f"### [[{title}]]")
            if chunk_id:
                lines.append(f" _(from {chunk_id})_")
            lines.append(f"\n{summary}\n\n")
            total += 1

    lines.append(f"\n---\n_Total: {total} articles_\n")
    INDEX.write_text("".join(lines))

    # Push to wiki git repo
    try:
        subprocess.run(["git", "-C", str(WIKI_DIR), "add", "-A"], check=True, capture_output=True)
        subprocess.run(
            ["git", "-C", str(WIKI_DIR), "commit", "-m", f"compile: {total} articles"],
            check=True, capture_output=True,
        )
        subprocess.run(["git", "-C", str(WIKI_DIR), "push"], check=True, capture_output=True)
    except subprocess.CalledProcessError:
        pass  # Wiki git push is best-effort


def _find_by_title(title: str, category: str) -> Path | None:
    cat_dir = ARTICLES / category
    if not cat_dir.exists():
        return None
    for f in cat_dir.glob("*.md"):
        text = f.read_text(errors="replace")
        meta = _parse_frontmatter(text)
        if meta.get("title", "").lower() == title.lower():
            return f
    return None


def _first_paragraph(text: str) -> str:
    # Skip frontmatter
    if text.startswith("---"):
        end = text.find("---", 3)
        if end != -1:
            text = text[end + 3:].strip()
    # Skip headings
    lines = [l for l in text.splitlines() if l.strip() and not l.startswith("#")]
    if not lines:
        return ""
    return lines[0][:200]
