"""Semantic retrieval for wiki articles (Forge Prime v1.2, Enhancement A + F).

Runs at session start. Embeds the chunk spec + punch list, retrieves top-3
most similar articles from the wiki, returns their paths for the agent to read.

The embedding cache lives at ``~/.forge/prime/wiki/.embed-cache.json`` and is
regenerated by :func:`rebuild_index` after every ``forge compile``.

Retrieval events are logged to ``state.db.wiki_retrievals`` so the dashboard
can surface the most-referenced articles (Enhancement F).
"""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import List

from ._time import now_ist, to_iso

WIKI_DIR = Path.home() / ".forge" / "prime" / "wiki"
EMBED_CACHE = WIKI_DIR / ".embed-cache.json"


def _get_model():
    """Lazy import — only loaded when retrieval actually runs."""
    from sentence_transformers import SentenceTransformer
    return SentenceTransformer("all-MiniLM-L6-v2")


def _load_cache() -> dict:
    if EMBED_CACHE.exists():
        try:
            return json.loads(EMBED_CACHE.read_text())
        except (OSError, json.JSONDecodeError):
            return {}
    return {}


def _save_cache(cache: dict) -> None:
    EMBED_CACHE.parent.mkdir(parents=True, exist_ok=True)
    EMBED_CACHE.write_text(json.dumps(cache))


def rebuild_index() -> int:
    """Re-embed every article in wiki/articles/. Run after forge compile.

    Returns the number of articles indexed.
    """
    model = _get_model()
    cache: dict = {}
    articles_dir = WIKI_DIR / "articles"
    if not articles_dir.exists():
        _save_cache(cache)
        return 0
    for article_path in articles_dir.glob("**/*.md"):
        try:
            text = article_path.read_text()
        except OSError:
            continue
        if len(text.strip()) < 50:
            continue
        embedding = model.encode(text).tolist()
        cache[str(article_path.relative_to(WIKI_DIR))] = {
            "embedding": embedding,
            "length": len(text),
        }
    _save_cache(cache)
    return len(cache)


def retrieve(chunk_spec: str, top_k: int = 3) -> List[Path]:
    """Given a chunk spec, return top-K most semantically similar articles."""
    cache = _load_cache()
    if not cache:
        return []
    try:
        import numpy as np
    except ImportError:
        return []
    try:
        model = _get_model()
    except Exception:
        return []
    query_emb = np.array(model.encode(chunk_spec))
    query_norm = float(np.linalg.norm(query_emb))
    if query_norm == 0.0:
        return []
    scores: list[tuple[float, str]] = []
    for rel_path, data in cache.items():
        article_emb = np.array(data["embedding"])
        article_norm = float(np.linalg.norm(article_emb))
        if article_norm == 0.0:
            continue
        sim = float(np.dot(query_emb, article_emb) / (query_norm * article_norm))
        scores.append((sim, rel_path))
    scores.sort(reverse=True)
    return [WIKI_DIR / rel_path for _, rel_path in scores[:top_k]]


def log_retrieval(chunk_id: str, article_paths: List[Path], state_db_path: str) -> None:
    """Record that these articles were retrieved for this chunk (Enhancement F)."""
    if not article_paths:
        return
    try:
        conn = sqlite3.connect(state_db_path, isolation_level=None)
    except sqlite3.Error:
        return
    try:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS wiki_retrievals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                chunk_id TEXT,
                article_path TEXT,
                retrieved_at TEXT
            )
            """
        )
        ts = to_iso(now_ist())
        for article_path in article_paths:
            try:
                rel_path = str(Path(article_path).relative_to(WIKI_DIR))
            except ValueError:
                rel_path = str(article_path)
            conn.execute(
                "INSERT INTO wiki_retrievals (chunk_id, article_path, retrieved_at) "
                "VALUES (?, ?, ?)",
                (chunk_id, rel_path, ts),
            )
    except sqlite3.Error:
        pass
    finally:
        conn.close()
